CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,21 +32,20 @@ jobs:
           docker ps
 
       - name: Verify Backend & Frontend Health
-          run: |
-                echo "Waiting for services to become available..."
-                
-                # Target /api/ or /admin/login/ or your OpenAPI doc endpoint
-                curl --retry 10 --retry-delay 3 --retry-all-errors --fail http://localhost:8000/admin/login/ || {
-                  echo "Backend failed to respond!"
-                  docker compose logs backend
-                  exit 1
-                }
+        run: |
+          echo "Waiting for services to become available..."
+          
+          curl --retry 10 --retry-delay 3 --retry-all-errors --I http://localhost:8000/ || {
+            echo "Backend failed to respond!"
+            docker compose logs backend
+            exit 1
+          }
 
-                curl --retry 10 --retry-delay 3 --retry-all-errors --fail http://localhost:5173/ || {
-                  echo "Frontend failed to respond!"
-                  docker compose logs frontend
-                  exit 1
-                }
+          curl --retry 10 --retry-delay 3 --retry-all-errors --fail http://localhost:5173/ || {
+            echo "Frontend failed to respond!"
+            docker compose logs frontend
+            exit 1
+          }
 
       - name: Stop Services
         if: always()
